### ISSUE TITLE
Doc?

### ISSUE THREAD

**Issue by mysteryx93** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#14]
What happened to the repository doc? It got forked a a few times and the doc got lost along the way -- I've been digging for a 
while trying to find basic syntax and still haven't found it; would be faster to look at the source code.

Edit: ok found the doc just within the VapourSynth folder. But it's hard to read, the formatting isn't great, and it doesn't tell the plugin namespace.

**Comment by Asd-g** [comment]
Namespace is added.

Pull requests for the reformatting are welcome.

**Comment by mysteryx93** [comment]
Readme links on the root page top are broken

**Comment by Asd-g** [comment]
Thanks.
