### ISSUE TITLE
_EncodedFrameBottom and _EncodedFrameTop

### ISSUE THREAD

**Issue by realfinder** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#17]
same as https://github.com/Asd-g/MPEG2DecPlus , they can be used for hybrid sources https://forum.doom9.org/showpost.php?p=1967491&postcount=13

**Comment by Asd-g** [comment]
Try the latest version.

**Comment by realfinder** [comment]
it seems work fine, thanks
