### ISSUE TITLE
_DurationNum and _DurationDen swap places?

### ISSUE THREAD

**Issue by realfinder** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#21]
Compared with [MPEG2DecPlus](https://github.com/Asd-g/MPEG2DecPlus) or it's MPEG2DecPlus bug?

**Comment by Asd-g** [comment]
Here they are ok (https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/commit/ffa730121fd593cd0c2f5ac05e37e50f4322c450).

I fixed them in RawSourcePlus but obviously I didn't in D2VSource.

**Comment by realfinder** [comment]
I will close this then, but what if D2VSource one is the correct? https://forum.videohelp.com/threads/404451-What-does-FPSden-mean-in-AVISynth#post2645025

**Comment by Asd-g** [comment]
Check [this comment](https://github.com/HolyWu/L-SMASH-Works/pull/18#discussion_r618076561).

**Comment by realfinder** [comment]
I got it now, thanks
