### ISSUE TITLE
L-Smash error with ex_bob(nnedi3=true), AnimeITVC(1)

### ISSUE THREAD

**Issue by kedaitinh12** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#23]
L-Smash error with ex_bob(nnedi3=true) when deinterlaced video, Screenchange repeat. I know That's L-Smash not setting field parity switch correctly to frame props. Use DGSource and works fine (ex_bob() honors frame props over GetParity())
More detail from here:
https://forum.doom9.org/showthread.php?p=1973984#post1973984

**Comment by kedaitinh12** [comment]
I had more problem when use with AnimeITVC(1). After deinterlaced, video had glitched, artifaced
Example: https://mega.nz/file/YeQ1jDiT#B2AvjCC-39XxxDjen67Hllt2l5UxK2fmtStfZbJuuP8

**Comment by Asd-g** [comment]
What happens if you remux the file from the first comment in to .mkv?

About the second comment - can you elaborate? Is the video ok before deinterlacing?

**Comment by kedaitinh12** [comment]
I remuxed the file from the first comment in to .mkv and it work correctly. Thanks
About the second comment - No, video is interlacing before deinterlacing but after deinterlacing, video still interlacing

**Comment by Asd-g** [comment]
What's the frame number you have issue?
Did you test if the issues persist with another deinterlacer?

**Comment by kedaitinh12** [comment]
> What's the frame number you have issue? Did you test if the issues persist with another deinterlacer?

I think error was fixed if use with another deinterlacer
