### ISSUE TITLE
LSmashAudioSource distorts PCM Audio Streams in Standard MOV files from Nikon and in MP4 from Panasonic cam

### ISSUE THREAD

**Issue by Stereoway** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#26]
Hi,

I was advised from doom9 forum to place this issue here. 

When using LSmash as source filter in Avisynth, all my standard Full-HD MOV files from Nikon D5100, Nikon D5300 and 4K-MP4 from Panasonic G9 are completely distorted at full volume. Video-Stream is fine. Audio is also fine with LWLibavAudioSource or FFAudioSource but forces unwanted indexing just for audio.

G9 audio is: 
PCM big/signed / Code-ID: twos / 2 channels / 48.0 kHz / 16 bits / Constant 1.526 kb/s

D5100/D5300 audio is: 
PCM little/signed / Code-ID: sowt / rest as above

I am happy to provide samples.
Thank you

**Comment by Asd-g** [comment]
Hi,

Yes, a short sample will helpful.

**Comment by Stereoway** [comment]
Hi,

I got some new insights. The file with LSmash-Audio issues is export from my video-editor EDIUS (NLE). It is encoded with ProRes (Proxy in this case with tiny 80x60 video to save space) but with untouched pcm_s16le. 

It plays well with good audio with MPV, VLC-Player, Windows-Media-Player and VDub2 opened directly. But it has distorted audio if you open it with Avisynth like this:

AudioDub(LSmashVideoSource("...blabla.mov"),LSmashAudioSource("...blabla.mov"))
Return last
 
Sample file:
https://user-images.githubusercontent.com/120655123/208422615-d36dc393-308d-41c1-854c-ee3ad0a8050b.mov

Thank you!

**Comment by Stereoway** [comment]
Hi,
merry Christmas to everybody!
Just to add one more finding: There is no problem if the file has 24bit-Audio.
Thanks.

**Comment by Asd-g** [comment]
Hi,

it's an old bug in liblsmash ( https://github.com/l-smash/l-smash/issues/91 ). If you

**Comment by Asd-g** [comment]
Try the latest version.
