### ISSUE TITLE
Compiles, but doesn't run properly with glib2 .74.*

### ISSUE THREAD

**Issue by Wisperer** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#29]
As stated it will compile, but trying to run it results on in undefined symbol error. I've been able to replicate this on at least 3 systems.

OS: Arch Linux

Using Vapoursynth

```
libgobject-2.0.so.0: undefined symbol:atomic_rc_box_release_full```

**Comment by Asd-g** [comment]
Just tested on Debian bullseye and vspipe runs without issues (VapourSynth R58). Try to update the compiler and the dependencies if you not already.

**Comment by Wisperer** [comment]
oh i tracked things down. 

For starters Debian bullseye is on glib 2.66.8. I'm on 2.74.1 so the newest lib bricks it.

The newest version i got working was glib 2.73.3

**Comment by Asd-g** [comment]
Tested with Debian sid (glib 2.74.5) and no issue too.

**Comment by Wisperer** [comment]
Hm. Maybe 2.74.5 fixed the issue.  I first encountered the issue on 3.74.1

**Comment by Wisperer** [comment]
Ignore the typo

**Comment by Asd-g** [comment]
Reopen if there is further issue.
