### ISSUE TITLE
fail build in linux (VS part)

### ISSUE THREAD

**Issue by sl1pkn07** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#3]
Hi

with l-smash c98781ca3eafc60f92e4bd956e69c03d646dc007 (if help)

~~~
gcc -Os -ffast-math -Wall -std=c99 -pedantic -I. -I. -I../include -fPIC -I/usr/local/include  -fexcess-precision=fast  -c ../common/lwindex.c -o ../common/lwindex.o
../common/lwindex.c: In function 'create_index':
../common/lwindex.c:2087:23: error: storage size of 'file_stat' isn't known
 2087 |         struct stat64 file_stat;
      |                       ^~~~~~~~~
../common/lwindex.c:2088:9: warning: implicit declaration of function 'stat64'; did you mean 'stat'? [-Wimplicit-function-declaration]
 2088 |         stat64( lwhp->file_path, &file_stat );
      |         ^~~~~~
      |         stat
../common/lwindex.c:2087:23: warning: unused variable 'file_stat' [-Wunused-variable]
 2087 |         struct stat64 file_stat;
      |                       ^~~~~~~~~
../common/lwindex.c: In function 'parse_index':
../common/lwindex.c:2774:19: error: storage size of 'file_stat' isn't known
 2774 |     struct stat64 file_stat;
      |                   ^~~~~~~~~
../common/lwindex.c:2783:5: error: unknown type name 'off_t'
 2783 |     off_t pos = ftell( index );
      |     ^~~~~
../common/lwindex.c:2784:39: warning: format '%x' expects argument of type 'unsigned int *', but argument 3 has type 'int *' [-Wformat=]
 2784 |     if( fscanf( index, "<File1MXXH=0x%x>\n", &file_1m_xxhash ) != 1 )
      |                                      ~^      ~~~~~~~~~~~~~~~
      |                                       |      |
      |                                       |      int *
      |                                       unsigned int *
      |                                      %x
../common/lwindex.c:2774:19: warning: unused variable 'file_stat' [-Wunused-variable]
 2774 |     struct stat64 file_stat;
      |                   ^~~~~~~~~
make: *** [GNUmakefile:27: ../common/lwindex.o] Error 1
~~~

greetings

**Comment by msg7086** [comment]
Please use the currently maintained version at https://github.com/HolyWu/L-SMASH-Works/ .

**Comment by sl1pkn07** [comment]
Hi
what is the difference between HolyWu and this one? part of obviously effort for build with Avisynth+?

greetings

**Comment by realfinder** [comment]
HolyWu seems will not do any update from now on since he made the project read only

aside from that, don't know if HolyWu or msg7086 see the updates here https://github.com/l-smash/l-smash and if it relate to L-SMASH-Works

aside from that, @msg7086, isn't better to add Asd-g as a member to HomeOfAviSynthPlusEvolution?

**Comment by msg7086** [comment]
If he doesn't update, then we can repurpose this repo for future updates.

l-smash is not very well related to l-smash-works. l-smash is a demuxer, while l-smash-works uses l-smash as a demuxer, and uses ffmpeg as a decoder. Most changes in l-smash have very little impact on l-smash-works -- unless they solve particular bugs in l-smash-works.

Already invited 4 days ago but not accepted yet. Let me know if I should add others to the org. My new job doesn't allow me to spend much time on those filters anymore so I'd be happy to let someone else handle the projects.

**Comment by realfinder** [comment]
I think repurpose is needed now, there are no uptodate repo other than small updates in https://github.com/AkarinVS/L-SMASH-Works and he/she don't care about avs/avs+ at all!

**Comment by msg7086** [comment]
Sure. We can rebase our changes off holywu's and others' commits, force push to master, and then develop upon that.
