### ISSUE TITLE
Crash when ÅÄÖ is in path.

### ISSUE THREAD

**Issue by starinspace** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#30]
We use a lot of åäö in my country and in most cases the software crashes. I don't know if this is something with L-SMASH-Works, but it works correctly with other plugins in avisynth. However it does work correctly when åäö is not used in path.

**Comment by Asd-g** [comment]
How did you run the script? A quick test with `ffplay -i 1.avs -autoexit` doesn't show issues. `1.avs`:
```
LWLibavVideoSource("åäö.hevc")
```
