### ISSUE TITLE
errors when creating an index file, latest update (2023.04.30)

### ISSUE THREAD

**Issue by kakazex** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#31]
Now the index file is often not created immediately, sometimes only with 3-5+ attempts. Even if the path and names are completely in english. +does not copy the file name (index file), or leaves it empty or writes some nonsense from characters

**Comment by Asd-g** [comment]
Attached two test versions. Try if they work properly for you.

What's your `Current system locale` in Windows.
Did you set `Beta: Use Unicode UTF-8 for worldwide language support`?
What's the avs+ version you're using?

[tests.zip](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/files/11402008/tests.zip)

**Comment by kakazex** [comment]
by the way, I noticed that the new versions have become lighter, by ~1 mb.
> [tests.zip ](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/files/11402008/tests.zip)

both work, even with non-english.
avs+ last, 3.7.2

**Comment by Axiom21** [comment]
I am having a decoding & encoding error with L-Smash in RipBot264.
When importing a new video file into the app, it displays a Decoding Error, previous build was OK.
Just read how to enable the Unicode UTF-8 in Windows 11, so I will try that tomorrow as well as the test files you posted.
Will reply back...

**Comment by Axiom21** [comment]
OK, due to my decoding error, I didn't think that the UTF-8 change would do anything, and it didn't.
However, both test#1 & #2 solved my decoding problems.
So hopefully you can release a "fixed" L-Smash build, soon.
Regards

PS:- using AVS 3.7.3 r3982
