### ISSUE TITLE
_EncodedFrameTop / Bottom maybe wrong?

### ISSUE THREAD

**Issue by MIRIMIRIM** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#32]
I have such a clip

<table width="220px">
    <tr>
        <td style="width:120px">Source Frame</td>
        <td style="width:30px" colspan="2">0</td>
        <td style="width:20px" colspan="3">1</td>
        <td style="width:30px" colspan="2">2</td>
        <td style="width:20px" colspan="3">3</td>
    </tr>
    <tr>
        <td style="width:120px">TFF flag</td>
        <td style="width:30px" colspan="2">1</td>
        <td style="width:20px" colspan="3">1</td>
        <td style="width:30px" colspan="2">0</td>
        <td style="width:20px" colspan="3">0</td>
    </tr>
    <tr>
        <td style="width:120px">RFF flag</td>
        <td style="width:30px" colspan="2">0</td>
        <td style="width:20px" colspan="3">1</td>
        <td style="width:30px" colspan="2">0</td>
        <td style="width:20px" colspan="3">1</td>
    </tr>
    <tr>
        <td style="width:120px">Field</td>
        <td style="width:10px">0t</td>
        <td style="width:10px">0b</td>
        <td style="width:10px">1t</td>
        <td style="width:10px">1b</td>
        <td style="width:10px">1t_r</td>
        <td style="width:10px">2b</td>
        <td style="width:10px">2t</td>
        <td style="width:10px">3b</td>
        <td style="width:10px">3t</td>
        <td style="width:10px">3b_r</td>
    </tr>
    <tr>
        <td style="width:120px">Decode Frame</td>
        <td style="width:20px" colspan="2">0</td>
        <td style="width:20px" colspan="2">1</td>
        <td style="width:20px" colspan="2">2</td>
        <td style="width:20px" colspan="2">3</td>
        <td style="width:20px" colspan="2">4</td>
    </tr>
</table>

Top three columns are from clip headers, field column is the result I think we should get. “_r” means repeat.

> _EncodedFrameTop [int], _EncodedFrameBottom [int]
> Frame number (before pulldown) used to generate this frame's top/bottom field.

But I got the following props when use `LWLibavVideoSource(clip, repeat=True)`:

frame | _EncodedFrameTop | _EncodedFrameBottom
--- | --- | ---
0 | 0 | 0
1 | 1 | 1
2 | 2 | 2
3 | 2 | 3
4 | 3 | 4

I’m not sure what went wrong.

**Comment by Asd-g** [comment]
Can you share a short sample?

**Comment by MIRIMIRIM** [comment]
I use mmg trim the first few frames from the original DVD source

[sample.zip](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/files/11529990/sample.zip)

**Comment by Asd-g** [comment]
Thanks.

**Comment by Asd-g** [comment]
Try the attached test version.

Use `ffprobe -show_frames sample.mkv` to get the frames metadata.

[LSMASHSource.zip](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/files/11594511/LSMASHSource.zip)

**Comment by MIRIMIRIM** [comment]
Thank you for the fix, at the same time I realized that I was looking at the wrong order of frames and have fixed the issue description.
