### ISSUE TITLE
fails opening avc file

### ISSUE THREAD

**Issue by Selur** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#33]
Using [this](https://drive.google.com/file/d/1TZnrCm3LMcbZTk6UkWg2n5EpwdtERVzu/view?usp=share_link) file, LibavSMASHSource and LWLibavSource both simply crash. (tried the last 5 releases)
Using DGSource or ffms2 works fine.

**Comment by Asd-g** [comment]
1280x533 is not valid YUV 4:2:0 resolution.

![Untitled](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/assets/65298684/e776753d-4d63-431b-9c85-eca5f96d62a2)

![Untitled1](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/assets/65298684/37f823ac-f494-4777-8ca2-dc3e560e4ec3)

**Comment by Selur** [comment]
MPC-HC and ffplay both play the file fine.
Mediainfo reports:
```
Width                                    : 1280
Width                                    : 1 280 pixels
Height                                   : 533
Height                                   : 533 pixels
Original height                          : 534
Original height                          : 534 pixels
Stored_Height                            : 544
Sampled_Width                            : 1280
Sampled_Height                           : 534
```
so it seems like the height flag of the container is wrong, the flag of the video seems to be right.
=> the file isn't really 533, but 534

**Comment by Asd-g** [comment]
`ffprobe -show_streams file" reports stream 533 height.
`exiftool file" reports stream 533 height.

ffms2 reads the file but the height is 532.
