### ISSUE TITLE
Feature Request: Support audio channel mask with Avs+ r4001

### ISSUE THREAD

**Issue by tebasuna51** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#35]
The last Avs+ r4001 support the audio property Channel Mask included in VideoInfo struct.

See the new Avisynth.h in https://github.com/AviSynth/AviSynthPlus/blob/master/avs_core/include/avisynth.h
to know how it is stored in the existing int image_type.

Audio decoders must fill that info like do in audio_output.cpp:

...
 vi->nchannels                = output_channels;
 vi->audio_samples_per_second = aohp->output_sample_rate;
...
Now we need:
 vi-> image_type = ...

**Comment by Asd-g** [comment]
Try the attached version.

[LSMASHSource_test.zip](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/files/12051984/LSMASHSource_test.zip)

**Comment by tebasuna51** [comment]
Seems work fine for me with some samples ac3, eac3 and dts 
I'll continue testing with other samples.

**Comment by FranceBB** [comment]
Thanks for the Channel Mask property support, works like a charm in the stable build. :)
Now we just need ffmpeg support and we're good to go in production. :D
