### ISSUE TITLE
06 and 07 aren't working anymore

### ISSUE THREAD

**Issue by almosely** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#36]
Just wanted to report that I have updated from L-SMASH-Works (2022-11-09) to the newest and it did not work for me anymore. I tried to play a youtube video from 2017 ...

LWLibavVideoSource("Federer.vs.Nadal.720p.HD.Australian.Open.Final.2017.mkv", format="YUV420P8", prefer_hw=1)

Video
ID : 1
Format : AVC
Format/Info : Advanced Video Codec
Format profile : High@L4.1
Format settings : CABAC / 7 Ref Frames
Format settings, CABAC : Yes
Format settings, Reference frames : 7 frames
Codec ID : V_MPEG4/ISO/AVC
Duration : 3 h 18 min
Bit rate : 3 778 kb/s
Width : 1 280 pixels
Height : 720 pixels
Display aspect ratio : 16:9
Frame rate mode : Constant
Frame rate : 59.940 (60000/1001) FPS
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 8 bits
Scan type : Progressive
Bits/(Pixel*Frame) : 0.068
Stream size : 5.24 GiB (96%)
Default : Yes
Forced : No

... but it stuttered and had pixel errors all over. Hardware is GeForce GTX 660 TI and Core i7-3770. Windows 10.

Then I tried backwards until L-SMASH-Works (2023-05-07) is working for me again. So 06 and 07 aren't working anymore. I am using the newest AVS+ 64 and my C++ Runtimes are up to date too. Just my 2ct.

**Comment by Asd-g** [comment]
Can you try yo update the GPU drivers if they are not the latest?

**Comment by almosely** [comment]
I had indeed an old GPU driver installed, but for my GTX 660 Ti there are only security updates available anymore. But I updated today to the latest. The problem is still the same.

**Comment by Asd-g** [comment]
Try the attached version.

[LSMASHSource.zip](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/files/12261919/LSMASHSource.zip)

**Comment by tebasuna51** [comment]
The new seems work fine for me.

**Comment by almosely** [comment]
Tried with the same source as above and the new version is working fine. Thank you! :-)

**Comment by Asd-g** [comment]
Thanks for testing. It's ffmpeg issue.

@tebasuna51, @almosely, can you test the attached new version?

[LSMASHSource_test1.zip](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/files/12267702/LSMASHSource_test1.zip)

**Comment by almosely** [comment]
test1 is working too :-)

**Comment by Asd-g** [comment]
[20230806 1129.0.1.0](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/releases/tag/1129.0.1.0)

**Comment by almosely** [comment]
Works like a charm, thank you :-)

**Comment by kedaitinh12** [comment]
Hi, some slow when compared with ffms2 and DGindexNV
https://forum.doom9.org/showthread.php?p=1990489#post1990489

**Comment by tebasuna51** [comment]
No problem using LWLibavVideoSource, LSMASHVideoSource seems have some problems even over .mp4

**Comment by Asd-g** [comment]
If you mean the slower speed of LSMASHVideoSource, then it's probably related to the lsmash demuxing.

**Comment by Asd-g** [comment]
@almosely, @tebasuna51  can you  test the attached version if it's ok with prefer_hw=1?

[LSMASHSource.zip](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/files/12750734/LSMASHSource.zip)

**Comment by tebasuna51** [comment]
Still LWLibavVideoSource is fast than LSMASHVideoSource over mp4

**Comment by Asd-g** [comment]
I wanted to know if the issue from the op is there (stuttering and bad pixels).

If you want to further test both LWLibavVideoSource and LSMASHVideoSource you can try [these versions](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/issues/41#issuecomment-1732639226).

**Comment by Asd-g** [comment]
[This](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/issues/41#issuecomment-1751477897) is the reason for the worse performance of LSMASHVideoSource compared to LWLibavVideoSource.
