### ISSUE TITLE
stream_index=-1 stops working after choosing different or nonexistent audio track

### ISSUE THREAD

**Issue by flossy83** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#39]
For the Avisynth version of LwLibavAudioSource, for a source with no audio track #5:

```
LWLibavAudioSource(source, stream_index=-1)  # works as expected

LWLibavAudioSource(source, stream_index=5)  # error message as expected, since there is no 5th audio track in the source

LWLibavAudioSource(source, stream_index=-1)  # no longer works, keeps trying to select track 5 again?
```

Regenerating the cache file resolves the issue.

**Comment by Asd-g** [comment]
`stream_index=-1` is meant for initial use before creating the index file. After if you use `stream_index` it should be with value >=0 (the specific stream).

**Comment by flossy83** [comment]
Sorry to reopen this but this issue caught me out again today and wasted half an hour scratching my head trying to figure out why audio was not working -- it was because I had changed the audio track to track #2 and then forgot that this required me to manually delete the cache file before resetting stream_index back to its default value (-1 or undefined).

Are we sure we don't want to change this behaviour?

**Comment by Asd-g** [comment]
`r1164` should be ok.

**Comment by flossy83** [comment]
Thanks

**Comment by flossy83** [comment]
Noooo it's still happening, [here](https://drive.google.com/file/d/1jU-pwu3saCh-5P6o1HRgav_5ORDoaghd/view?usp=sharing) is a small test file to reproduce it.

Track 1 contains the main audio, track 2 contains silent audio (I don't know why this exists, it's in the TV broadcast, maybe they use it for "audio description" narration or something)

`LWLibavAudioSource(stream_index=-1)  # selects track 2 (wrong, but ok whatever)`
`LWLibavAudioSource(stream_index=1)   # selects track 1 (correct)`
`LWLibavAudioSource(stream_index=-1)  # selects track 1 again (huh?)`

*Manually delete .lwi cache file*

`LWLibavAudioSource(stream_index=-1) # selects track 2 `

**Comment by Asd-g** [comment]
Both audio streams have same channels number and both have `DISPOSITION:default=0` (not default audio). So in this case FFmpeg chooses to play the latest audio as default. Run `ffprobe -i audiotest.ts` to verify that the second audio is played.

`LWLibavAudioSource(stream_index=-1)  # selects track 2 (wrong, but ok whatever)`
`LWLibavAudioSource(stream_index=1)   # selects track 1 (correct)`
`LWLibavAudioSource(stream_index=-1)  # selects track 1 again (huh?)`

About the  second `stream_index=-1` (the latest line) - if you use `stream_index=-1` after you already used `stream_index>=0`, the first stream in order is picked. In this case the first stream in order is different than the default stream. So I have to change it to pick the default stream.

**Comment by Asd-g** [comment]
@flossy83, you try `r1167`.

**Comment by flossy83** [comment]
Thanks that solves the issue where stream_index=-1 was incorrectly selecting track 1 again. 

Ideally I think it should select track 1 when stream_index=-1, because according to MediaInfo the 2 tracks have ID's 0x65 and 0x66 and if ffmpeg sees that then it should select track 0x65 as I presume that would be the "first detected audio stream" although I don't know what is meant by "detected" or "latest audio" as you wrote.
