### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by Asd-g** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#4]
I could add the updates from https://github.com/HolyWu/L-SMASH-Works and https://github.com/AkarinVS/L-SMASH-Works, and build a release.
Is it better I do it into master branch or new one, @msg7086?

Not to spam the other issue (https://github.com/HomeOfAviSynthPlusEvolution/neo_f3kdb/issues/7) - I could make new release in case you (@msg7086) don't have time to do it.

Maybe it would be better to create a team discussion for such discussions?

**Comment by msg7086** [comment]
I force pushed master. Let's take holy's branch as base and work on that.

And please tag and release all new versions if you can take over. Let me know if you have insufficient permissions.

Feel free to create a team discussion. I can also join a telegram channel.
