### ISSUE TITLE
LSMASHVideoSource decreasing performance

### ISSUE THREAD

**Issue by Dendraspis** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#41]
Hello,
I ran into a performance issue when using `LSMASHVideoSource()` in `AviSynth` - `VapourSynth` not tested yet.
Not sure if that is "normal" or if I missed something. Maybe someone can enlighten me?

When using a fast GPU-accelerated encoder like [NVEncC](https://github.com/rigaya/NVEnc) along with a very long video source file, it becomes very obvious. In my case the source file is a 24h 1080p video file extracted from YouTube with ~2600k frames and I used StaxRip when using `NVEncC`'s possibility to directly load the avs-script, so some of the screenshots are from StaxRip, but same result when using `avs2pipemod64` directly via `cmd`. `AviSynth` version is the latest official `v3.7.3` and `L-SMASH-Works` is the latest official release `20230806 1129.0.1.0`.

At the beginning everything works as intended and NVEncC is running with ~190fps @ 50% VE:
![image](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/assets/50659978/25ab0e52-4ded-49d8-b881-146e907ff4c3)
![image](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/assets/50659978/34a8589f-b940-4392-9679-e8a636960d42)

After about 80k frames you start to recognize a slight decrease in performance - very slowly. After around 130k frames I had around 160fps left @ 23% VE:
![image](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/assets/50659978/fc77a32c-83e8-4eaa-93d6-26e16a4d6f9c)

And after 400k frames 55fps @ 8% VE:
![image](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/assets/50659978/9a64f0ac-109b-4b98-bbc9-771c437d45bb)

At about 50% after more than 1100k frames the encoding speed stagnates at ~18fps - sadly no screenshot was made.

This is absolutely reproducible with  `LSMASHVideoSource()` , whereas `LWLibavVideoSource()` has no problems of this sort as far as I can tell.
`LWLibavVideoSource()` after ~2050k frames with ~190fps @ 50% VE:
![image](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/assets/50659978/4ea25477-d287-45ce-ae2b-7658010edf4c)

---------
Command line:
`A:\Path\to\avs2pipemod\avs2pipemod64.exe -dll=A:\Path\to\AviSynth\AviSynth.dll -y4mp "A:\YouTube\Video\XXXXXXXXXX.avs" | A:\Path\to\NVEncC\NVEncC64.exe  --cqp 30 --codec h265 --preset P7 --output-depth 10 --profile main10 --colormatrix bt709 --colorprim bt709 --transfer bt709 --y4m -i - -o "A:\YouTube\Video\XXXXXXXXXX_encode.h265"`

---------
AviSynth Script:
```python
LoadPlugin("A:\Path\to\L-SMASH-Works\LSMASHSource.dll")
LSMASHVideoSource("A:\YouTube\Video\XXXXXXXXXX.mp4")
```

---------
<details><summary>Media Info of source file:</summary>
<p>

```
General
Complete name                            : .\XXXXXXXXXX.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 37.1 GiB
Duration                                 : 24 h 0 min
Overall bit rate                         : 3 688 kb/s
Frame rate                               : 25.000 FPS
Writing application                      : Lavf58.67.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 2 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 2 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 24 h 0 min
Bit rate                                 : 3 553 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.069
Stream size                              : 35.7 GiB (96%)
Title                                    : ISO Media file produced by Google Inc.
Writing library                          : x264 core 155 r2901 7d0ff22
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 24 h 0 min
Bit rate mode                            : Constant
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 1.29 GiB (3%)
Title                                    : ISO Media file produced by Google Inc.
Default                                  : Yes
Alternate group                          : 1
```

</p>
</details>

**Comment by Mr-Z-2697** [comment]
I have that experience too.
Kinda known issue maybe?
https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/issues/36#issuecomment-1686226176

**Comment by Asd-g** [comment]
Can you test these versions:
- https://github.com/HolyWu/L-SMASH-Works/releases/tag/20210423
- https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/releases/tag/20220505

**Comment by Asd-g** [comment]
This behavior is by design. Accessible point for every requested frame have to be found. For every next frame (n+1) the searching of accessible point takes more time than the time required to find the accessible point for the previous frame (n).

**Comment by Dendraspis** [comment]
Thanks for the information, will check it out soon.  🙂
