### ISSUE TITLE
Error with indexing .avi video

### ISSUE THREAD

**Issue by kedaitinh12** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#42]
Hi, I got an error with LWLibavVideoSource when I was indexing the .avi video. I got "LWLibavVideoSource: bgr0 is not supported"

Scripts: LoadPlugin("C:\Megui\MeGUI-2944-64\tools\lsmash\LSMASHSource.dll")
LWLibavVideoSource("C:\Users\ADMIN\Downloads\Result without denoising.avi")

Video: https://www.mediafire.com/file/voxhxk97qd7qk2d/Result_without_denoising.avi/file

**Comment by Asd-g** [comment]
You can try the latest version r1141.

**Comment by kedaitinh12** [comment]
it's work, thanks
