### ISSUE TITLE
Indexing Bluray source but got green color some frame

### ISSUE THREAD

**Issue by kedaitinh12** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#43]
I tried indexing some Bluray source but got green color in some frame, I'm indexing with LWLibavVideoSource via .lwi file, i change to DGDecNV and don't have that errors

Source:
https://terabox.com/s/1DagosBK8dUmTQjvC9cpKQw

**Comment by Asd-g** [comment]
I can't download the video without registration or without download some app.

**Comment by kedaitinh12** [comment]
Yeah, that need Terabox PC app and account to download

**Comment by Asd-g** [comment]
I wouldn't download that app or create an account.

If the container isn't mkv, try remuxing the video in mkv.

**Comment by kedaitinh12** [comment]
ok, i tried remux .m2ts to .mkv but i got green sceens from frame 8435 to 8447

Script: LWLibavVideoSource("F:\New folder\BDMV\PLAYLIST\New folder_00001.mkv", cachefile="F:\New folder\BDMV\PLAYLIST\New folder_00001.lwi")

Video without login and app: https://mega.nz/file/ZnkQTBbD#JtQs7cwnt2t1BIGLkzRgjEftQr1jYEspNU_WBnxIKX4

**Comment by Asd-g** [comment]
Thanks for the sample.

Don't use eac3to (Haali muxer) to remux in mkv. It's very outdated and it's the culprit of such issues.

Using eac3to to demux the video in .h264 and using mkvtoolnix (mkvmerge) to remux the video in .mkv leads to no issues.
Also eac3to will throw a lot of warnings ("Video has a gap of 1 frames at playtime ...") when demuxing the video.

**Comment by kedaitinh12** [comment]
After remux with mkvmerge, I don't meet errors anymore but I meet other errors. After Index, the video is only half-length, I need to add fpsnum and fpsden to fix it
change from
LWLibavVideoSource("C:\Users\ADMIN\Downloads\00002.mkv")
to
LWLibavVideoSource("C:\Users\ADMIN\Downloads\00002.mkv", fpsnum=30000, fpsden=1001)

Video: https://mega.nz/file/Zv8HXYiR#viZda7EFCSKRiomolQwrj7FljmsJ3tMeQnPx9MrpUOo

**Comment by Asd-g** [comment]
Try with `repeat=false`.

**Comment by kedaitinh12** [comment]
Ok, it's work now
