### ISSUE TITLE
Read RPU data while using prefer_hw=1

### ISSUE THREAD

**Issue by erazortt** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#45]
Using the following script I was not able to get any RPU related frame props:
LWLibavVideoSource("clip.ts", prefer_hw=1, stream_index=1)

however when this does add the RPU data
LWLibavVideoSource("clip.ts", stream_index=1)

Would it be possible to have the RPU data added when prefer_hw is enabled?
Or is that impossible due to the hw nature of the reading?

**Comment by Asd-g** [comment]
Try the attached version.

[LSMASHSource.zip](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/files/12864649/LSMASHSource.zip)

**Comment by erazortt** [comment]
nope, also with that version I'm not getting the DolbyVisionRPU when prefer_hw=1.

**Comment by Asd-g** [comment]
The NVIDIA/Intel decoder doesn't support this at the moment.

**Comment by Asd-g** [comment]
@erazortt, I didn't test with NVIDIA/Intel decoder but the latest version `r1266` has RPU frame property with DXVA2 and D3D11 hw decoder.
