### ISSUE TITLE
'LSMASHAudioSource: no valid audio frame' trying to read .mov generated by AJA Kona capture card

### ISSUE THREAD

**Issue by youer-mam** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#46]
I have an AJA Kona LHe+ capture card and LSMASHAudioSource can't open the files it generates.  After sitting for about 15 seconds it gives 'LSMASHAudioSource: no valid audio frame.'  Video is raw yuv422p10le and audio is a single pcm_s24le stereo track, but other video/audio codecs give the same error.

LWLibavAudioSource works fine but the files I'm working with are huge (100+ gb) and take forever to index.

If I run the files through ffmpeg with vcodec/acodec copy LSMASHAudioSource does work, so there's something about the AJA output it doesn't like.

Sample file:
https://ia904605.us.archive.org/2/items/untitled_23_202310/untitled_23.mov

**Comment by Asd-g** [comment]
Thanks for the sample.

l-smash cannot read the file.
Try to save in another container (mp4) (if the capture card has such option).
You can report the issue in [this fork](https://github.com/vimeo/l-smash) (it's more active than the original repo).
