### ISSUE TITLE
Fails to build on FreeBSD 13.2 aarch64

### ISSUE THREAD

**Issue by diizzyy** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#47]
See https://lists.freebsd.org/archives/freebsd-pkg-fallout/2023-October/500325.html
Version: 20230716

**Comment by Asd-g** [comment]
Use the newer versions (>= [1141.0.0.0 ](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/tree/1141.0.0.0)). They have SSE2 code separated in own source files. Also [Cmake](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/blob/1141.0.0.0/CMakeLists.txt) building is available that detects if CPU supports SSE2.
