### ISSUE TITLE
Problem decoding h264 stream with versions 1144 and 1147

### ISSUE THREAD

**Issue by JoGillis** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#48]
While decoding some h264 stream (from mkv file, demuxed with mkvtoolnix without issues), both versions become very slow, seems to generate only full green frames and seems not to decode the whole file.
Other streams processed in the same way work fine. 
I'm using AviSynthPlus 3.7.3 from Avs2Pipemod (64 bit and 32 bit give the same behaviour).
The script: 
LWLibavVideoSource("xxxxx.h264", prefer_hw = 3 )

tried also the other prefer_hw values:
3: not working as reported
2: should be Intel-> not working
1: Nvidia-> working
0: Software-> working

As I understand 3 should try Nvidia first, so why is it not working by default as the order described in the doc is: CUVID->QSV and cuvid seems to be working?

Also version 1126 (20230507) works fine with the same script/drivers, so is somewhere between version 1126 and 1144 something changed that did introduce this?

As there is a workaround, I can continue, 

Drivers:
Intel® Graphics Driver 31.0.101.2115 for 6th-10th Gen Intel® Core™ Processor Graphics, and related Intel Atom®, Pentium®, and Celeron® processors. Version: 31.0.101.2115 Release date: December 29, 2022
Nvidia: 537.42 (Quadro M3000M)

**Comment by Asd-g** [comment]
Can you try the attached version?

[LSMASHSource.zip](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/files/13314655/LSMASHSource.zip)

**Comment by JoGillis** [comment]
The first (very quick) test seems to be working. I'll try to test more options/cases later.

PS: is there a way to know which decoding path is taken with prefer_hw=3?

**Comment by Asd-g** [comment]
The attached version exports variable `LWLDECODER` (only for `LWLibavVideoSource`). You can use it like:

```
LWLibavVideoSource(...)
Subtitle(LWLDECODER)
```
[LSMASHSource.zip](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/files/13371383/LSMASHSource.zip)
