### ISSUE TITLE
r1147. [Fatal]: Failed to avformat_open_input

### ISSUE THREAD

**Issue by pr0zitiv** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#49]
Windows 10
AviSynthPlus_3.7.2_20220317
AvsPmod v2.7.4.6 (Windows x86-64)

The error appears if there are Cyrillic characters in the file path or file name.
r1144 works fine

**Comment by Asd-g** [comment]
Use [the latest AvsPmod](https://github.com/gispos/AvsPmod/blob/GPo/changelog.txt#L46).

**Comment by kedaitinh12** [comment]
> Use [the latest AvsPmod](https://github.com/gispos/AvsPmod/blob/GPo/changelog.txt#L46).

In megui, i can index utf 8 filename without error with DGDecNV and ffms2

**Comment by kedaitinh12** [comment]
And I tried with latest AvsPmod, the error still continues

**Comment by pr0zitiv** [comment]
> Use [the latest AvsPmod](https://github.com/gispos/AvsPmod/blob/GPo/changelog.txt#L46).

This is bug r1147, reproduced also on AvsPmod_v2.7.5.5

**Comment by Asd-g** [comment]
Actually it's still [AvsPmod issue](https://forum.doom9.org/showthread.php?p=1993769#post1993769).

Until AvsPmod is fixed you have few options:
- Use another app for previewing like VirtualDub2.
- Do not use Cyrillic characters.
- Enable UTF-8 code pages in Windows - `Windows Settings > Time & language > Language & region > Administrative language settings > Change system locale, and check Beta: Use Unicode UTF-8 for worldwide language support.`

**Comment by pr0zitiv** [comment]
[https://i.ibb.co/mFyzpb5/clipboard.png](url)
I'll stay with version r1144

**Comment by kedaitinh12** [comment]
@pr0zitiv AvsPmod work with latest L-Smash-Works now with enable UTF-8 code pages in Windows - Windows Settings > Time & language > Language & region > Administrative language settings > Change system locale, and check Beta: Use Unicode UTF-8 for worldwide language support and Boulder [suggestion](url=https://forum.doom9.org/showthread.php?p=1993776#post1993776)

**Comment by Asd-g** [comment]
@pr0zitiv, make sure you saved the avs script as UTF-8 and not ANSI.

**Comment by kedaitinh12** [comment]
gispos explain about AvsPmod 2.7.5.5
https://forum.doom9.org/showthread.php?p=1993861#post1993861

**Comment by gispos** [comment]
Uhhhm...
1147 only works with UTF-8. If a program can't handle system languages, that's very bad.
For example, I want to see my German umlauts displayed correctly in Subtitle and this is not possible with Avisynth and UTF-8.
And this is not due to AvsPmod, VirtualDub also only outputs one character garbage.

**Comment by kedaitinh12** [comment]
Did you check with latest ffms2?
https://forum.doom9.org/showthread.php?p=1993748#post1993748

**Comment by gispos** [comment]
Just found the Utf8 option in Subtitle (embarrassing), but the source filters should still be able to use the system language. 
Thanks kedaitinh12, I will test it.

**Comment by Asd-g** [comment]
Try the new version `r1156`.

**Comment by gispos** [comment]
"Try the new version r1156."

Just as it should be ,)  Thank you!
I also had private reasons for this, I have programs that I wrote almost 15 years ago and that can only do ANSI.
Changes are only possible with effort: Virtual machine with Win7 and then install old programmer IDE.

**Comment by pr0zitiv** [comment]
> @pr0zitiv AvsPmod work with latest L-Smash-Works now with enable UTF-8 code pages in Windows - Windows Settings > Time & language > Language & region > Administrative language settings > Change system locale, and check Beta: Use Unicode UTF-8 for worldwide language support.

Unfortunately, this breaks the display of local fonts

**Comment by pr0zitiv** [comment]
> Try the new version `r1156`.

thanks, everything is working again )
