### ISSUE TITLE
Add DRC parameter to LSMASH/LWLibavAudioSource()

### ISSUE THREAD

**Issue by tebasuna51** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#5]
All players have a option to override the Dynamic Range Compression included in some AC3 files.
Also ffmpeg have the parameter -drc_scale 0

But with 
LSMASH/LWLibavAudioSource() we can't override the compression and the decoded volume don't match the source volume when DRC data is present.
This is a big problem to transcode audio.

Attached sample files encoded with DRC: Film Standard and DRC: None
[Samples.zip](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/files/6747139/Samples.zip)

The film file have only a
Dynamic Range Compression min/max : -6,59 / 3,52 dB
but DRC can go until -24/+24 dB

See also https://forum.doom9.org/showthread.php?p=1945716#post1945716

**Comment by Asd-g** [comment]
[LSMASHSource_drctest.zip](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/files/6884881/LSMASHSource_drctest.zip)

Try this test build. It's x64 and only LWLibavAudioSource has the additional parameter `float "drc_scale" (default 1.0)`.

**Comment by tebasuna51** [comment]
Thanks Asd-g, your release 20210728 works fine for me with the drc_scale parameter.

Only a typo in the README:
 + drc_sclae (defalut: 1.0)
