### ISSUE TITLE
Can't decode .avi file

### ISSUE THREAD

**Issue by kedaitinh12** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#50]
L-SMASH-Works index this video normaly but when i try play with preview, i got error: "can't read avs frame"
https://drive.google.com/file/d/1gmnpk4vOf9Lt04RdlQYhqzkIycd2dgvw/view?usp=drivesdk

**Comment by Asd-g** [comment]
Try `r11601.

**Comment by kedaitinh12** [comment]
yeah, it works but it has blocky from frame 56 to 284. I tried muxed.mkv but error is still there

**Comment by Asd-g** [comment]
`ffmpeg -i input.avi -vcodec copy output.h264` works.

**Comment by kedaitinh12** [comment]
I tested with AvsPmod and got errors:
frame 51
![New File5100000_4](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/assets/66716952/1ce1f0da-2614-46b2-88c1-07ccfe98c1a6)
frame 66
![New File6600000_4](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/assets/66716952/174ef6ff-5fa5-4eb6-97aa-c9224dd09b86)
script:
LoadPlugin("C:\Encode Tools\MeGUI-2944-64\tools\lsmash\LSMASHSource.dll")
LoadPlugin("C:\Encode Tools\MeGUI-2944-64\tools\ffms\ffms2.dll")
a=FFVideoSource("C:\Users\ADMIN\Downloads\Aitai - SE7VN PV.avi", fpsnum=30000, fpsden=1001, threads=1, colorspace="YUV420P8")
b=LWLibavVideoSource("C:\Users\ADMIN\Downloads\Aitai - SE7VN PV - Copy.avi")
StackVertical(a.subtitle("ffms2", size=30),b.subtitle("L-Smash", size=30))

**Comment by kedaitinh12** [comment]
> `ffmpeg -i input.avi -vcodec copy output.h264` works.

ok, I know what you said now. After using it and work now
