### ISSUE TITLE
Pixel format error

### ISSUE THREAD

**Issue by gispos** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#54]
If format = "", an error is issued.

**Comment by Asd-g** [comment]
I guess you used `format=""` only for the test?

**Comment by gispos** [comment]
No, unfortunately not.
I use it in all my scripts (over 2000) as a standard file template in AvsPmod.

SourceFile = ScriptDir() + [***]
SourceFile = Exist(SourceFile) ? SourceFile : ***
video=LWLibavVideoSource(SourceFile, indexingpr=False, cache=False, format="")
audio=LWLibavAudioSource(SourceFile, cache=False, av_sync=True)
audioDub(video, audio)

If it is really too difficult to handle an empty string, then I would have to change all my scripts.
So it would be nice if you could change that. For this reason I still use the older version, because there are no problems with it.

Greetings

**Comment by Asd-g** [comment]
The new version should be ok.

**Comment by gispos** [comment]
Yes, it works. Nice. Thank you.
