### ISSUE TITLE
Decode Failure

### ISSUE THREAD

**Issue by RyougiKukoc** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#55]
Source: [u2](https://u2.dmhy.org/details.php?id=30195&hit=1) DISC1 00005.m2ts Frame 31300
I tried rolling back until 20210811, this is the last release which decodes normally at this frame

Script: 
```python
from vapoursynth import core
core.std.LoadPlugin(r"xxx\L-SMASH-Works-20210811\x64\LSMASHSource.dll")
core.lsmas.LWLibavSource('00005.m2ts').set_output()
```

Normal / Fail decoded frame comparison: https://slow.pics/c/jaHj7kZ6

**Comment by Asd-g** [comment]
The link requires email, password... Can you share the sample in other place that doesn't require email/password?

**Comment by RyougiKukoc** [comment]
I uploaded the m2ts file [here](https://github.com/RyougiKukoc/Assets/releases/tag/240228)

**Comment by Mr-Z-2697** [comment]
I've had this problem too, but it only seems to happen when **seeking** (including the sample provided by OP), so I ignored it.
I have a sample that has much smaller size, [here](https://workupload.com/file/2CDh8A36ypa). I belive they have the same problem, even produced by the same encoder (based on the scaling list found in PPS).
The file has several problematic frames, for example frame 25 and 1198.

**Comment by Asd-g** [comment]
Thanks for the samples.

20210811 works for the Mr-Z-2697 sample too. I have to check the ffmpeg updates.

**Comment by Asd-g** [comment]
Can you test the attached version (it lacks some additional libs, so it's only for testing this issue).

[LSMASHSource.zip](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/files/14471822/LSMASHSource.zip)

**Comment by Mr-Z-2697** [comment]
It works

**Comment by Asd-g** [comment]
Yes, it's about indexing. With FFmpeg >= 5.0 the extradata is  stripped. [This commit](https://github.com/FFmpeg/FFmpeg/commit/e5af9203098a889f36b759652615046254d45102) is the culprit.

**Comment by Asd-g** [comment]
Try the new version `r1170`.

**Comment by Mr-Z-2697** [comment]
Sorry, this just looks like the same function in a different place, how does that affect the indexing results? Please enlight me.😂

**Comment by Asd-g** [comment]
You can compare the index files - https://www.diffchecker.com/2zWc8GDI/

**Comment by Mr-Z-2697** [comment]
I already compred them when I tested the test build.
I didn't express myself correctly before, I meant "how it affects indexing process", sorry

**Comment by Asd-g** [comment]
https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/blob/1170.0.0.0/common/lwindex.c#L1584

It's not only in different place but it also doesn't have path to be externally accessed and `parser_ctx->parser->split` is NUL.
