### ISSUE TITLE
prefer_hw fails to find AV1 QSV decoder when libdav1d is enabled in FFmpeg

### ISSUE THREAD

**Issue by qyot27** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#57]
Tried with mode 2 and mode 3, and neither one finds av1_qsv, and falls back to software decoding with libdav1d as verified by checking the value of LWLDECODER (as well as by the CPU load/playback timing not being able to keep up at 4K).  Only by forcing it on using *decoder="av1_qsv"* does it actually engage the AV1 decoder on my Arc A770.

prefer_hw can find the QSV decoders for H264, HEVC, and VP9 without issue.

After rebuilding FFmpeg *without* libdav1d enabled, prefer_hw was able to detect av1_qsv, but since there is no native av1 decoder, you have to have a graphics card capable of handling it.  I'm not sure if libdav1d stopping prefer_hw from working correctly is due to FFmpeg's av1dec preference tree or an issue that can be worked around in prefer_hw.

**Comment by Asd-g** [comment]
Try the attached version.

[LSMASHSource.zip](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/files/14505154/LSMASHSource.zip)

**Comment by qyot27** [comment]
Yep, that fixes the issue.

**Comment by qyot27** [comment]
Re-opening because I did test the other two situations (only libaom without libdav1d, and both enabled), and yeah, libaom-av1 needs to be checked for too.  If both are enabled alongside libvpl, then the libdav1d match is enough to get prefer_hw to engage, but if only libaom and libvpl are enabled, then it won't fall back.

So the check just needs to be expanded to
```
        else if (!strcmp(codec->name, "libdav1d") || !strcmp(codec->name, "libaom-av1"))
            codec_name = "av1";
```
