### ISSUE TITLE
20240304 1170.0.0.0 regression - the lwi file is always recreated instead of using the cache

### ISSUE THREAD

**Issue by FranceBB** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#58]
Starting with version 20240304 1170.0.0.0 there's a regression about using the lwi files.
The version before the latest release was checking whether there was an lwi file in the same directory as the file and if it was written with the same version of LWLibav.
If it was written with an older version, then it would recreate the lwi index, otherwise it would use the one it found.
In this new version, however, it recreates the lwi file every single time, not just with AVSPmod mod but also with ffmpeg and any other application.
For instance, in this very same unchanged script, we have two different command lines calling ffmpeg and it's recreating the index files both times:

```
video=LWLibavVideoSource("V:\fs0\clip.dir\HSM00342.mxf", cache=true)
ch12=LWLibavAudioSource("V:\fs0\clip.dir\HSM00342.mxf", stream_index=1, cache=true)
ch34=LWLibavAudioSource("V:\fs0\clip.dir\HSM00342.mxf", stream_index=2, cache=true)
ch56=LWLibavAudioSource("V:\fs0\clip.dir\HSM00342.mxf", stream_index=3, cache=true)
ch78=LWLibavAudioSource("V:\fs0\clip.dir\HSM00342.mxf", stream_index=4, cache=true)
audio=MergeChannels(ch12, ch34, ch56, ch78)
AudioDub(video, audio)
```

![image](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/assets/18946343/b47f135c-764f-4f4d-a82d-5dfc61dff162)

Setting **cache=true** doesn't affect it as it keeps recreating it anyway and it's set to true by default anyway even when it's left unspecified.
I tried with cachefile but it is still recreating it:

```
video=LWLibavVideoSource("V:\fs0\clip.dir\HSM00342.mxf", cache=true, cachefile="V:\fs0\clip.dir\HSM00342.mxf.lwi")
ch12=LWLibavAudioSource("V:\fs0\clip.dir\HSM00342.mxf", stream_index=1, cache=true, cachefile="V:\fs0\clip.dir\HSM00342.mxf.lwi")
ch34=LWLibavAudioSource("V:\fs0\clip.dir\HSM00342.mxf", stream_index=2, cache=true, cachefile="V:\fs0\clip.dir\HSM00342.mxf.lwi")
ch56=LWLibavAudioSource("V:\fs0\clip.dir\HSM00342.mxf", stream_index=3, cache=true, cachefile="V:\fs0\clip.dir\HSM00342.mxf.lwi")
ch78=LWLibavAudioSource("V:\fs0\clip.dir\HSM00342.mxf", stream_index=4, cache=true, cachefile="V:\fs0\clip.dir\HSM00342.mxf.lwi")
audio=MergeChannels(ch12, ch34, ch56, ch78)
AudioDub(video, audio)
```

Even changing the disk didn't change a thing:

```
video=LWLibavVideoSource("A:\Ingest\MEDIA\temp\HSM00342.mxf", cache=true, cachefile="A:\Ingest\MEDIA\temp\HSM00342.mxf.lwi")
ch12=LWLibavAudioSource("A:\Ingest\MEDIA\temp\HSM00342.mxf", stream_index=1, cache=true, cachefile="A:\Ingest\MEDIA\temp\HSM00342.mxf.lwi")
ch34=LWLibavAudioSource("A:\Ingest\MEDIA\temp\HSM00342.mxf", stream_index=2, cache=true, cachefile="A:\Ingest\MEDIA\temp\HSM00342.mxf.lwi")
ch56=LWLibavAudioSource("A:\Ingest\MEDIA\temp\HSM00342.mxf", stream_index=3, cache=true, cachefile="A:\Ingest\MEDIA\temp\HSM00342.mxf.lwi")
ch78=LWLibavAudioSource("A:\Ingest\MEDIA\temp\HSM00342.mxf", stream_index=4, cache=true, cachefile="A:\Ingest\MEDIA\temp\HSM00342.mxf.lwi")
audio=MergeChannels(ch12, ch34, ch56, ch78)
AudioDub(video, audio)
```

![image](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/assets/18946343/4cb80c5e-dbf1-4058-a00b-67c2e3ef2cb6)

adding a simple:

`tweak(sat=1.31, dither=true)`

as an example, makes it recreate the .lwi

![image](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/assets/18946343/05bf9f8a-10d9-491b-91eb-298166ee780a)

**Comment by flossy83** [comment]
I am unable to test right now but can you confirm the issue does NOT occur with [20240112 1167.0.0.0](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/releases/tag/1167.0.0.0) as I would like to rule that out.  
Thanks

**Comment by Asd-g** [comment]
Try the attached version.

[LSMASHSource_1177.zip](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/files/14545956/LSMASHSource_1177.zip)

**Comment by FranceBB** [comment]
Amazing, thank you so much asd, as always.
The fix worked like a charm, I just tested it.

**Comment by tuanden0** [comment]
@Asd-g:

This issue still exists on build 1194.0.0.0

It's always re-create LWI file and not use the exists LWI

For example my AVS:
`a=LWLibavAudioSource("source.mkv", 1)
c=LWLibavVideoSource("source.mkv", format="YUV420P8", prefer_hw=1)
a=AssumeFPS(a, 24000, 1001)
c=AssumeFPS(c, 24000, 1001)
AudioDub(c, a)
`

**Comment by Asd-g** [comment]
Try the script with [AVSMeter](https://forum.doom9.org/showthread.php?t=174797) -  running few times `avsmeter64 scripts.avs -o -timelimit=2` should create lwi index file only for the first time. Or if you prefer ffmpeg - run few time `ffmpeg -i script.avs -c copy -f null -`.

**Comment by tuanden0** [comment]
@Asd-g 

I re-check with your CLI and confirm that the LWI file not be re-created

Then, I check my encode flow and found out
First, I review the video source file with this AVS script on AvsPmod:

> LWLibavVideoSource("E:\Download\z\source.mkv", prefer_hw=1)
> AssumeFPS(24000, 1001)

Then, it created new LWI file.

After that I encoded with this AVS script:

> a=LWLibavAudioSource("source.mkv", 1)
> c=LWLibavVideoSource("source.mkv", format="YUV420P8", prefer_hw=1)
> a=AssumeFPS(a, 24000, 1001)
> c=AssumeFPS(c, 24000, 1001)
> AudioDub(c, a)

And it recreated LWI file.

I am not sure this is issue or this is feature of L-SMASH.

**Comment by msg7086** [comment]
Can you check if you are using the same dll binary? Like maybe one of the app is 32 bit and the other is 64 bit?

**Comment by tuanden0** [comment]
@msg7086 

I checked that I only install 64 bit version of AVS+ and 64 bit L-SMASH

Just to make sure, I empty folder `plugins` and `plugins+` and it still happend

**Comment by Asd-g** [comment]
It's expected behavior. With script `s.avs` you create index file with no active audio stream. With script `s2.avs` you create index file with active audio stream.

Compare the index files from both files to see the diff.

**Comment by tuanden0** [comment]
@Asd-g

I understood, thank for your help
