### ISSUE TITLE
Error opening MPEG-TS files: Error getting frame property "_Matrix"

### ISSUE THREAD

**Issue by JJKylee** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#6]
- L-SMASH-Works version: 20210728 (`LWLibavVideoSource` on AviSynth+ 3.7.0)
- Video sample: [here](https://4kmedia.org/lg-new-york-hdr-uhd-4k-demo/) (MPEG-TS, HEVC, 10bit HDR)

Here's the script code:

```
LoadPlugin("D:\Utilities\StaxRip\Apps\Plugins\Dual\L-SMASH-Works\LSMASHSource.dll")
LWLibavVideoSource("D:\Test\LG New York HDR UHD 4K Demo (PQ).ts", cachefile="D:\Test\LG New York HDR UHD 4K Demo (PQ)_temp\temp.lwi", prefer_hw=0, format="YUV420P10")
```

And the screenshot of the error (AvsPmod v2.6.8.7)

![L-SMASH-Works_TS_error_20210728](https://user-images.githubusercontent.com/3157518/127409257-8f97677a-f5b6-4495-be95-61b3e1612cba.png)

```
Error getting frame property "_Matrix": property is not set
([ScriptClip], line 1)
```

This is the same video opened with HolyWu's 20210423 build:

![L-SMASH-Works_HolyWu_opening_TS_20210728](https://user-images.githubusercontent.com/3157518/127410906-850a0994-aef5-4f1b-9f4b-5a4fb82f7b27.png)

And the same video opened with `ffms2` (87bae19 StvG, [here](https://forum.doom9.org/showthread.php?p=1928993#post1928993))

![ffms2_opening_TS_20210728](https://user-images.githubusercontent.com/3157518/127409890-f21b69b0-058e-4c5f-b328-17213a2077e2.png)

**Comment by Asd-g** [comment]
You can try the latest version.

**Comment by JJKylee** [comment]
It works alright now. Many thanks. 😊

**Comment by JJKylee** [comment]
Sorry, but I was hasty in closing this issue thread.

Now the preview opens OK but the **pixel type** is incorrectly set to `YV12` by default (without the `format` option) for the same file, whose actual pixel type is `YUV420P10`.

**Comment by Asd-g** [comment]
I guess you're testing with hardware decoding again because with software decoding I cannot reproduce the issue.
Try this test ver if it's ok with hardware decoding.
[LSMASHSource_testhw.zip](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/files/6904396/LSMASHSource_testhw.zip)

**Comment by JJKylee** [comment]
Thanks.

With the new binary, I've run into this weird phenomenon.

The first [PQ HDR10 sample](https://4kmedia.org/lg-new-york-hdr-uhd-4k-demo/) opens well with or without `prefer_hw=1` (cache file deleted before each load).

**Software decoding:**

![L-SMASH-Works_TS_HDR_PQ_20210729](https://user-images.githubusercontent.com/3157518/127585318-20f539d2-0d73-4d07-8fd1-a94bfbdeacfb.png)

**Hardware decoding:**

![L-SMASH-Works_TS_HDR_PQ_HW_20210729](https://user-images.githubusercontent.com/3157518/127585361-08241bfc-c4af-48e3-ae7c-2bc5a34b5777.png)

However, with the [HLG HDR sample](https://4kmedia.org/travelxp-4k-hdr-hlg-sample/), it's weird.

**Software decoding:** works well

![L-SMASH-Works_TS_HDR_HLG_20210729](https://user-images.githubusercontent.com/3157518/127585592-252b7d07-cad4-4117-96a9-2c46e327cbc2.png)

But when I delete the cache file and put hardware decoding option, the pixel type becomes weird.

**Hardware decoding:**

![L-SMASH-Works_TS_HDR_HLG_HW_20210729](https://user-images.githubusercontent.com/3157518/127585674-7e31b799-fdf6-4c46-876f-8ee45389fc69.png)

I have no clue. 😓

**Comment by Asd-g** [comment]
What's NVIDIA driver version? You need 456.71 or newer.
Do older LSMASHSource versions decoding correctly?
Any difference if you remux the file into mkv?
Unfortunately I don't have NVIDIA GPU to test myself.

**Comment by JJKylee** [comment]
> What's NVIDIA driver version?

My Nvidia driver is _NVIDIA Studio driver_ 471.41 (the most recent one released on July 19, this year).

> Do older LSMASHSource versions decoding correctly?

I tested with HolyWu's 20210423 build, and have found that it suffers **the same issue**. I was not testing it thoroughly back then and didn't find it out. 😓

> Any difference if you remux the file into mkv?

I'm observing a very weird phenomenon here. Although the reported pixel type of the AviSynth+ script is `YUV420P8`, the resulting pixel type becomes `YUV420P10` if stream-copy-remuxed to MKV via `mkvmerge`.

```
--------------------------- AviSynth Script ---------------------------

LoadPlugin("D:\Utilities\StaxRip\Apps\Plugins\Dual\L-SMASH-Works\LSMASHSource.dll")
LWLibavVideoSource("D:\Test\TravelXP 4K HDR HLG Demo (HLG).ts", cachefile="D:\Test\TravelXP 4K HDR HLG Demo (HLG)_temp\temp.lwi", prefer_hw=1)

------------------------- Source Script Info -------------------------

Width     : 3840
Height    : 2160
Frames    : 14665
Time      : 04:53.300
Framerate : 50 (50/1)
Format    : YUV420P8

------------------------- Target Script Info -------------------------

Width     : 3840
Height    : 2160
Frames    : 14665
Time      : 04:53.300
Framerate : 50 (50/1)
Format    : YUV420P8

---------------------------- Muxing to MKV ----------------------------

mkvmerge 59.0.0

D:\Utilities\MKVToolNix\mkvmerge.exe -o "D:\Test\TravelXP 4K HDR HLG Demo (HLG).mkv" --no-audio --no-subs --no-chapters --no-attachments --no-track-tags --no-global-tags "D:\Test\TravelXP 4K HDR HLG Demo (HLG).ts" --no-video --no-subs --no-chapters --no-attachments --no-track-tags --no-global-tags --audio-tracks 1 --language 1:und --track-name "1:" --default-track 1:0 --forced-track 1:0 "D:\Test\TravelXP 4K HDR HLG Demo (HLG).ts" --ui-language en

...
...

General
Complete name            : D:\Test\TravelXP 4K HDR HLG Demo (HLG).mkv
Format                   : Matroska
Format version           : Version 4
File size                : 698 MiB
Duration                 : 4 min 59 s
Overall bit rate         : 19.6 Mb/s
Encoded date             : UTC 2021-07-30 02:03:14
Writing application      : mkvmerge v59.0.0 ('Shining Star') 64-bit
Writing library          : libebml v1.4.2 + libmatroska v1.6.4

Video
ID                       : 1
Format                   : HEVC
Format/Info              : High Efficiency Video Coding
Format profile           : Main 10@L5.1@Main
Codec ID                 : V_MPEGH/ISO/HEVC
Duration                 : 2 min 40 s
Bit rate                 : 36.1 Mb/s
Width                    : 3 840 pixels
Height                   : 2 160 pixels
Display aspect ratio     : 16:9
Frame rate mode          : Variable
Frame rate               : 91.145 FPS
Original frame rate      : 50.000 FPS
Color space              : YUV
Chroma subsampling       : 4:2:0
Bit depth                : 10 bits
Bits/(Pixel*Frame)       : 0.048
Stream size              : 691 MiB (99%)
Writing library          : ATEME Titan File 3.7.6 (4.7.6.0)
Default                  : Yes
Forced                   : No
Color range              : Limited
Color primaries          : BT.2020
Transfer characteristics : HLG
Matrix coefficients      : BT.2020 non-constant

...
...
```

Now I suspect it can be a driver issue. But I'm totally at a loss now. 😖

**Comment by JJKylee** [comment]
For comparison, I used `DGDecNV`(=`DGIndexNV` + `DGSource`), another indexer + source filter that can frameserve video files _using Nvidia graphics card_ to open the above mentioned [HLG HDR video](https://4kmedia.org/travelxp-4k-hdr-hlg-sample/).

For reference, `DGSource` decodes the video stream using the Nvidia graphics card _without any particular option by default_, based on its `dgi` index file generated by `DGIndexNV`. When the source file has 10-bit depth, the decoded video is delivered as 16-bit and is reported to Avisynth+ as pixel format `P016`(`YUV420P16`).

The script code is as follows.

```
LoadPlugin("D:\Utilities\StaxRip\Settings\Plugins\Dual\DGDecNV\DGDecodeNV.dll")
DGSource("D:\Test\TravelXP 4K HDR HLG Demo (HLG)_temp\TravelXP 4K HDR HLG Demo (HLG).dgi")
```

And unlike `LWLibavVideoSource`, I could see that `DGSource` opens the TS file without issues.

![DGDecNV_DGSource_TS_HDR_HLG_HW_20210730](https://user-images.githubusercontent.com/3157518/127721657-07b0ba3f-bcd2-4037-94e0-c22369dd2d20.png)

So it turns out that it's not a video driver issue.

**Comment by Asd-g** [comment]
LWLibavVideoSource (software decoding) is giving the correct pixel type but the clip (`HLG HDR video`) isn't decoded properly. Check the first few frames.
FFmpeg is giving errors too.
Using ffmpeg to remux the video stream into .hevc and then using mkvmerge to remux it to mkv looks fine. Using mkvmerge to directly remux the video stream from .ts into mkv gives different result than the former process. I'm curious what result gives DGDecNV - similar to directly remuxing into mkv or remuxing into hevc+mkv.

Anyway, I would recommend to not rely ffmpeg decoding for .ts and similar.

**Comment by JJKylee** [comment]
Got it. Thanks for the detailed info.

**Comment by kedaitinh12** [comment]
Don't know if it's same issue with prefer_hw=1 in Vapoursynth, you can check and notice to AkarinVS. He will fix it in GPU support and Asd-g will backport to avisynth ver
