### ISSUE TITLE
THere is a problem when compiling on Ubuntu 22.04 using ffmpeg 6

### ISSUE THREAD

**Issue by NicTanghe** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#60]
❯  mkdir build && cd build
meson .. --optimization=3 --default-library=static -Db_lto=true -Dc_args="-march=native" -Dcpp_args="-march=native"
ninja -j$(nproc)
sudo cp libvslsmashsource.so /usr/lib/vapoursynth/
The Meson build system
Version: 0.61.2
Source dir: /home/nanghe/git_ubuntu22.4/av1/L-SMASH-Works/VapourSynth
Build dir: /home/nanghe/git_ubuntu22.4/av1/L-SMASH-Works/VapourSynth/build
Build type: native build
Project name: L-SMASH-Works
Project version: undefined
C compiler for the host machine: cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
C linker for the host machine: cc ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency vapoursynth found: YES 63
Run-time dependency liblsmash found: YES 2.16.1 rev.1477
Run-time dependency libavcodec found: YES 58.134.100
Run-time dependency libavformat found: YES 58.76.100
Run-time dependency libavutil found: YES 56.70.100
Run-time dependency libswscale found: YES 5.9.100
Build targets in project: 2
NOTICE: Future-deprecated features used:
 * 0.56.0: {'Dependency.get_pkgconfig_variable'}

L-SMASH-Works undefined

  User defined options
    default_library: static
    optimization   : 3
    b_lto          : true
    c_args         : -march=native
    cpp_args       : -march=native

Found ninja-1.10.1 at /usr/bin/ninja
[6/17] Compiling C object libvslsmashsource.so.p/.._common_decode.c.o
../../common/decode.c: In function ‘find_decoder’:
../../common/decode.c:106:31: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  106 |             preferred_decoder = select_hw_decoder( codec_name, 1, codecpar );
      |                               ^
../../common/decode.c:108:35: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  108 |                 preferred_decoder = select_hw_decoder( codec_name, 2, codecpar );
      |                                   ^
../../common/decode.c:111:31: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  111 |             preferred_decoder = select_hw_decoder( codec_name, prefer_hw_decoder, codecpar );
      |                               ^
[8/17] Compiling C object libvslsmashsource.so.p/.._common_lwlibav_video.c.o
FAILED: libvslsmashsource.so.p/.._common_lwlibav_video.c.o
cc -Ilibvslsmashsource.so.p -I. -I.. -I/usr/local/include -I/usr/local/include/vapoursynth -I/usr/include/x86_64-linux-gnu -fvisibility=hidden -flto=auto -fdiagnostics-color=always -DNDEBUG -Wall -Winvalid-pch -std=c99 -O3 -DXXH_INLINE_ALL -D_FILE_OFFSET_BITS=64 '-DDEFAULT_CACHEDIR=""' -mfpmath=sse -msse2 -march=native -fPIC -MD -MQ libvslsmashsource.so.p/.._common_lwlibav_video.c.o -MF libvslsmashsource.so.p/.._common_lwlibav_video.c.o.d -o libvslsmashsource.so.p/.._common_lwlibav_video.c.o -c ../../common/lwlibav_video.c
../../common/lwlibav_video.c: In function ‘lwlibav_video_setup_timestamp_info’:
../../common/lwlibav_video.c:367:55: error: ‘AVCodecParameters’ has no member named ‘framerate’
  367 |             *framerate_num = (int64_t)stream->codecpar->framerate.num;
      |                                                       ^~
../../common/lwlibav_video.c:368:55: error: ‘AVCodecParameters’ has no member named ‘framerate’
  368 |             *framerate_den = (int64_t)stream->codecpar->framerate.den;
      |                                                       ^~
[16/17] Compiling C object libvslsmashsource.so.p/.._common_lwindex.c.o
../../common/lwindex.c: In function ‘create_index’:
../../common/lwindex.c:2628:37: warning: implicit declaration of function ‘avformat_index_get_entries_count’ [-Wimplicit-function-declaration]
 2628 |         if( adhp->dv_in_avi == 1 && avformat_index_get_entries_count(format_ctx->streams[ adhp->stream_index ]) == 0 )
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../common/lwindex.c:2722:50: warning: implicit declaration of function ‘avformat_index_get_entry’ [-Wimplicit-function-declaration]
 2722 |                     write_av_index_entry( index, avformat_index_get_entry(stream, i) );
      |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~
../../common/lwindex.c:2722:50: warning: passing argument 2 of ‘write_av_index_entry’ makes pointer from integer without a cast [-Wint-conversion]
 2722 |                     write_av_index_entry( index, avformat_index_get_entry(stream, i) );
      |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                  |
      |                                                  int
../../common/lwindex.c:1913:25: note: expected ‘const AVIndexEntry *’ but argument is of type ‘int’
 1913 |     const AVIndexEntry *ie
      |     ~~~~~~~~~~~~~~~~~~~~^~
../../common/lwindex.c:2730:46: warning: initialization of ‘const AVIndexEntry *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 2730 |                     const AVIndexEntry *ie = avformat_index_get_entry(stream, i);
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~
../../common/lwindex.c:2743:50: warning: passing argument 2 of ‘write_av_index_entry’ makes pointer from integer without a cast [-Wint-conversion]
 2743 |                     write_av_index_entry( index, avformat_index_get_entry(stream, i) );
      |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                  |
      |                                                  int
../../common/lwindex.c:1913:25: note: expected ‘const AVIndexEntry *’ but argument is of type ‘int’
 1913 |     const AVIndexEntry *ie
      |     ~~~~~~~~~~~~~~~~~~~~^~
../../common/lwindex.c:2753:46: warning: initialization of ‘const AVIndexEntry *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 2753 |                     const AVIndexEntry *ie = avformat_index_get_entry(stream, i);
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~
../../common/lwindex.c: In function ‘parse_index’:
../../common/lwindex.c:2944:5: warning: writing into constant object (argument 3) [-Wformat=]
 2944 |     if( fscanf( index, "<ActiveVideoStreamIndex>%d</ActiveVideoStreamIndex>\n", &active_video_index ) != 1
      |     ^~
../../common/lwindex.c:2945:6: warning: writing into constant object (argument 3) [-Wformat=]
 2945 |      || fscanf( index, "<ActiveAudioStreamIndex>%d</ActiveAudioStreamIndex>\n", &active_audio_index ) != 1
      |      ^~
../../common/lwindex.c:2946:6: warning: writing into constant object (argument 3) [-Wformat=]
 2946 |      || fscanf( index, "<DefaultAudioStreamIndex>%d</DefaultAudioStreamIndex>\n", &default_audio ) != 1 )
      |      ^~
ninja: build stopped: subcommand failed.

**Comment by Asd-g** [comment]
FFmpeg > 6.0 is required ([more info](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/issues/18#issuecomment-1793804803)).
