### ISSUE TITLE
LSMASHAudioSource is broken

### ISSUE THREAD

**Issue by tebasuna51** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#63]
in the last (LSMASHSource.dll 2024/04/02) LSMASHAudioSource is broken (wrong channels and decode), use always LWLibavAudioSource than seems work fine. 

All wav files are informed with wrong number of channels and wrong decoded to 1 or 2 channels, even the stereo is decoded like mono.

For instance, for a standard 5.1 wav the MeGUI log show:

> --[Information] [04/04/2024 16:03:23] MediaInfo
> ---[Information] File: C:\tmp\6p321.wav
> ----[Information] SamplingRate: 48000
> ----[Information] Channels: 6
> ----[Information] ChannelPositionsString2: 3/2/0.1
> ...
> --[Warning] [04/04/2024 16:03:27] Channel count mismatch! The input file is reporting 6 channels and the AviSynth script is reporting 2 channels
> ...
> --[Information] [04/04/2024 16:03:27] AviSynth script
> ---[NoImage] LSMASHAudioSource("C:\tmp\6p321.wav", drc_scale=0.0)
> ---[NoImage] # detected channels: 6
> ---[NoImage] # detected channel positions: 3/2/0.1
> --[Information] [04/04/2024 16:03:28] Output Decoder
> ---[Information] [04/04/2024 16:03:28] Channels: 2

Without problems using LWLibavAudioSource

**Comment by L4cache** [comment]
Is L-SMASH reader supposed to read WAV files?

**Comment by Asd-g** [comment]
Try the attached version.

[LSMASHSource.zip](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/files/14892192/LSMASHSource.zip)

**Comment by Asd-g** [comment]
Try the latest version `r1192`.

**Comment by tebasuna51** [comment]
r1192 tested, LSMASHAudioSource now have correct channel count, but still don't read the MaskChannel in wav header like LWLibavAudioSource do.

**Comment by Asd-g** [comment]
Try the attached version.

[LSMASHSource.zip](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/files/14897629/LSMASHSource.zip)

**Comment by tebasuna51** [comment]
Now seems ok. Thanks

**Comment by tebasuna51** [comment]
To fast.
This .avs:

> LWLibavAudioSource("C:\tmp\8w3D.eac3", drc_scale=0)
> #LSMASHAudioSource("C:\tmp\8w3D.eac3", drc_scale=0)
> AudioDubEx(BlankClip(length=Int(1000*AudioLengthF(last)/Audiorate(last)), width=720, height=720, fps=25), last)
> Info()

Output correct maskchannel MaskChannels :  22031 (FL FR FC LF SL SR TFL TFR)
But with LSMASHAudioSource:

> AviSynth Open Failure
> LSMASHAudioSource [Fatal]: The number of tracks equal 0.

**Comment by Asd-g** [comment]
Can you share sample?

**Comment by tebasuna51** [comment]
[8w3D.zip](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/files/14899180/8w3D.zip)
Created with Audition 2007

I always use LWLibavAudioSource, I don't know if LSMASHAudioSource never support eac3.

**Comment by Asd-g** [comment]
`eac3` raw format isn't supported by l-smash.

If there is error message `The number of tracks equal 0.` it means that 99% of the cases the input file cannot be read by l-smash.

**Comment by tebasuna51** [comment]
You are right, even muxed in mkv or m2ts don't work.
I know the wiki info: "Recommended for MP4, MOV, [ISO Base Media] and its derived file formats."
But maybe need info about unssuported formats.

**Comment by Asd-g** [comment]
Anything different than should be considered non-supported:
* https://en.wikipedia.org/wiki/QuickTime_File_Format
* https://en.wikipedia.org/wiki/MP4_file_format
* https://en.wikipedia.org/wiki/3GP_and_3G2
* https://en.wikipedia.org/wiki/JPEG_2000
* https://en.wikipedia.org/wiki/Flash_Video
* https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format
