### ISSUE TITLE
LWLibavAudioSource crash

### ISSUE THREAD

**Issue by flossy83** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#64]
I don't know if this is worth fixing...cursed file `amarec(20200806-1406)_sample.avi` from the [doom9 test videos pack](https://drive.google.com/file/d/1-95lSEnxu3aGZS3WqwJPaYHSk4M7GSr9/view) I get a crash inside LWLibavAudioSource

![Untitled-1](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/assets/46382337/858ad055-67eb-4a5c-9cd0-433a5d39849c)

No problems playing just the video with LWLibavVideoSource, only the audio is the problem so I'm using FFAudioSource instead.

**Comment by Asd-g** [comment]
I cannot reproduce it with the following script:
```
BlankClip()
KillAudio()

a=LWLibavAudioSource("amarec(20200806-1406)_sample.avi")

AudioDub(a)
Info()
```

**Comment by flossy83** [comment]
Your example crashes for me, so it must be a problem with my system.

**Comment by flossy83** [comment]
Did some testing on my other machine and it crashes there too, but if I rollback to [20240304 1170.0.0.0](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/releases/tag/1170.0.0.0) then it doesn't crash.     The one after that is [20240317 1183.0.0.0](https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/releases/tag/1183.0.0.0) and that one crashes.  In the notes it says "removed depreciated leftover FFmpeg API (audio)" maybe it's related to that?

**Comment by flossy83** [comment]
I'm on Avisynth 3.7.3 r4003, 3.7, x86_64

**Comment by kedaitinh12** [comment]
> I'm on Avisynth 3.7.3 r4003, 3.7, x86_64 (latest public release)

Why you don't try with the beta build? It contains very many fix

**Comment by flossy83** [comment]
> > I'm on Avisynth 3.7.3 r4003, 3.7, x86_64 (latest public release)
> 
> Why you don't try with the beta build? It contains very many fix

Normally I would be using the latest beta but I switched over to the public release a few weeks ago for testing purposes of my project so that I know for sure it will be compatible with what the general public uses.

I tried just now with the latest beta 4066 and got the same result - does it crash for you as well?    Both of my machines are pretty much the same spec in terms of hardware and OS so it's not a very meaningful result that it crashes on both.

**Comment by Asd-g** [comment]
I found the issue (I can reproduce the issue).

**Comment by Asd-g** [comment]
Try the latest version `r1192`.

**Comment by flossy83** [comment]
> Try the latest version `r1192`.

All working on my end, much appreciated.
