### ISSUE TITLE
Fails to index 

### ISSUE THREAD

**Issue by jessielw** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#70]
Found a 1080p file that fails to index, but indexes with ffms2. 

`American.Gangster.2007.Extended.Version.Blu-ray.1080p.AVC.DTS-HD.MA.5.1.REMUX-FraMeSToR`

Let me know if you need it shared with you!

**Comment by jessielw** [comment]
I can share if needed

**Comment by Asd-g** [comment]
It seems the file is corrupted. There is a note: `Release is awaiting REPACK. Issue= small a/v freeze reported, and confirmed, @1h22m11s`

**Comment by jessielw** [comment]
Thanks for reporting that, I didn't see that issue where I got the source. Looking around I see what you mean now. I'll close this one as completed, sorry!
